# Generated by Django 2.0.1 on 2018-01-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wallet_support', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150)),
                ('volume', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=11, max_digits=12)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_pairs', to='arbitrage.Coin')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage.Coin')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage.Exchange')),
            ],
        ),
    ]
